#include "ota_app.h"
#include "stm32f4xx_hal.h"

/*
 * OneNET OTA transport adapter
 * ----------------------------
 * This watch project currently has only a UART/BLE data path and no TCP/IP or
 * HTTP client.  Bind these weak functions to the selected 4G/Wi-Fi/NB module.
 * The current OneNET general OTA southbound flow is:
 *
 *   POST /ota/device/version                         report version
 *   GET  /ota/south/check                            obtain task/token
 *   GET  /ota/south/download/{token} with Range      download package
 *   POST /ota/south/device/download/{token}/progress report progress
 *
 * OneNET's Authorization header is generated by the modem/network layer.  The
 * file uploaded to OneNET must be the .ota output produced by ota_pack.py, not
 * the raw Keil .bin file.
 */

__weak int onenet_ota_port_check(uint32_t current_version, onenet_ota_job_t *job)
{
    (void)current_version;
    (void)job;
    return ONENET_OTA_NO_UPDATE;
}

__weak int onenet_ota_port_download_range(const onenet_ota_job_t *job,
                                          uint32_t offset, uint8_t *buffer,
                                          uint32_t capacity,
                                          uint32_t *received)
{
    (void)job;
    (void)offset;
    (void)buffer;
    (void)capacity;
    if (received != NULL) {
        *received = 0U;
    }
    return ONENET_OTA_RETRY;
}

__weak void onenet_ota_port_report(const onenet_ota_job_t *job,
                                   ota_state_t state, uint8_t progress,
                                   ota_error_t error)
{
    (void)job;
    (void)state;
    (void)progress;
    (void)error;
}
